source "http://rubygems.org"
gem "log4r"
gem "rack"
gem "json"
gem "terminal-table"
gem "trollop"
gem "typhoeus"
gem "mongo", ">=1.8.1"
gem "hashery"
gem "domainatrix"
gem "whois"
gem "rubydns"
gem "actionpool"